# Generated by Django 4.1.1 on 2022-09-25 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220923_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4)], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Audio Interface', 'Audio Interface'), ('Audio Interface', 'Audio Interface')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('NY', 'New-York'), ('Texas', 'Texas')], max_length=100),
        ),
    ]
