# Generated by Django 4.1.1 on 2022-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4)]),
        ),
    ]
